### ISSUE TITLE
Tabs size

### ISSUE THREAD

**Issue by gj1118** [frankyonnetti/gravity-sublime-theme#11]
Hi , 
Can you please add a setting for decreasing the tab height, please ? 
Thanks 

With Regards
Gagan janjua

**Comment by frankyonnetti** [comment]
Can you give me an idea as to how much you would like the tabs decreased?

**Comment by gj1118** [comment]
If you can have multiple sizes it would be awesome. For example small would
correspond to half the width of the existing tab width, medium correponds
to three fourth the existing width.

Thanks

**Comment by frankyonnetti** [comment]
I don't have plans for changing the width, but I'll look at adding height options.

**Comment by gj1118** [comment]
Sorry I meant height instead of Width. My apologies for the same. The width
is absolutely fine.

---------------------------
With Regards
Gagan Janjua

**Comment by frankyonnetti** [comment]
Added a tab height option to 2.0.1:
"tab_height_short": true 
or, 
"tab_height_tall": true

**Comment by gj1118** [comment]
Thanks :)

---------------------------
With Regards
Gagan Janjua
