### ISSUE TITLE
Dark theme auto complete popup contrast

### ISSUE THREAD

**Issue by alexwhitman** [frankyonnetti/gravity-sublime-theme#12]
Can the contrast of the auto complete popup be improved?  The light background with the light 'unmatched' text doesn't make it easy to see the matches.

![gravity-popup](https://cloud.githubusercontent.com/assets/422013/5739703/4608c804-9bf4-11e4-9bbc-77157b847de4.png)

**Comment by frankyonnetti** [comment]
Sure, I can take a look.

**Comment by Twiebie** [comment]
Is it an idea to use the same colours as the command palette?

**Comment by frankyonnetti** [comment]
Changed the colors to match the command palette as @Twiebie suggested. It's not an exact match because they display differently.

Change is in version 2.0.1

**Comment by Twiebie** [comment]
Looks good, thanks!

**Comment by alexwhitman** [comment]
Much better, thanks. :+1:
