### ISSUE TITLE
Border of tabs is too thick, looks misaligned when left/right-most tabs are selected

### ISSUE THREAD

**Issue by pickx** [frankyonnetti/gravity-sublime-theme#13]
The gray border around tabs is designed to match to the OS X window borders, however it's one or two pixels too thick, so the corner looks wrong.
This is only noticeable on Reverse Gravity, but probably exists in Gravity as well.
Attached pics show how the corner looks compared to Finder tabs.
![screen shot 2015-01-21 at 13 01 33](https://cloud.githubusercontent.com/assets/4918121/5835283/57454c48-a16f-11e4-8b6c-d4e431ccb7b9.png)
![screen shot 2015-01-21 at 13 06 41](https://cloud.githubusercontent.com/assets/4918121/5835284/577aab54-a16f-11e4-8b50-138143e3e614.png)

!!!! EDIT: actually, I'm wrong about this. The reason it looks wrong is the lack of a gray border on the bottom of the tabs. Does Sublime allow this? !!!!

**Comment by frankyonnetti** [comment]
Thanks, I'll take a look.

**Comment by frankyonnetti** [comment]
This is fixed in 2.0.2 release. Thanks for pointing the display issue out.
