### ISSUE TITLE
Tab height should standardize

### ISSUE THREAD

**Issue by pickx** [frankyonnetti/gravity-sublime-theme#14]
The tabs in Reverse Gravity are slightly shorter than those in Gravity, which makes the switch between these two somewhat jarring. (I personally think the height in Reverse Gravity is more appropriate)

also, do you accept paypal donations?

**Comment by frankyonnetti** [comment]
When switching themes and to quickly bring back the file tabs, hit " Super + F ". 

If you would like to donate money, please donate to Package Control. They deserve it more than I do.
https://packagecontrol.io/about
