### ISSUE TITLE
tabs letter cut

### ISSUE THREAD

**Issue by giltig** [frankyonnetti/gravity-sublime-theme#16]
Hi,
I really like your new theme.
Letters like g being cut no matter what size of tabs.

![lettercut](https://cloud.githubusercontent.com/assets/5754742/5918541/860b1c3e-a632-11e4-816a-ac5b5b392065.png)

**Comment by frankyonnetti** [comment]
Thanks. I added a fix to version 2.0.4

It seems to be a bug with Sublime Text on Linux and Windows. 
https://github.com/jamiewilson/predawn/issues/35

To apply the fix, add this setting to your "Settings - User" file.
    "tab_font_small": true
