### ISSUE TITLE
JS syntax and more

### ISSUE THREAD

**Issue by giltig** [frankyonnetti/gravity-sublime-theme#17]
Hi,
I've noticed some syntax coloring is missing for javascript (e.g "this" saved keyword, json files without key value separation of color(although in sublime preferences there is a separation etc.).
Also in other languages.
![jsonwithoutsyntaxhighlight](https://cloud.githubusercontent.com/assets/5754742/5965209/0a31e3b8-a803-11e4-922b-6e56ab11bebb.png)

**Comment by frankyonnetti** [comment]
I'll take a look. Thanks.

**Comment by frankyonnetti** [comment]
This change is in version 2.0.5.

**Comment by giltig** [comment]
Actually I was wrong. There was a color to the JSON strings (like the original monokay) and the color is grey.
Please return the string colors of the JSON to be grey like it was before.

Thanks.

**Comment by frankyonnetti** [comment]
You don't like the green :-)

**Comment by giltig** [comment]
Well yeah:) but regardless I think that what's nice about your theme is
that it saves Sublime's default with a bit of modern twist and not changing
it completely.
The grey strings of the json that was before is actually nice - please put
it back:)

**Comment by frankyonnetti** [comment]
I put the gray color back and added color to 'this' in v.2.0.6.

**Comment by giltig** [comment]
Thanks.
