### ISSUE TITLE
File icons in windows

### ISSUE THREAD

**Issue by giltig** [frankyonnetti/gravity-sublime-theme#18]
Hi,
Some of the file icons appear only after clicking on the directory tree.
Some like .scss doesn't appear at all.
![image](https://cloud.githubusercontent.com/assets/5754742/6059105/a037fe5a-ad36-11e4-99a7-96712a5a5e25.png)
![image](https://cloud.githubusercontent.com/assets/5754742/6059114/aadd88b6-ad36-11e4-8bad-4e6fb051b1e1.png)

Furthermore - this keyword in javascript does not have syntax color..
Thanks.

**Comment by frankyonnetti** [comment]
I'm not seeing the missing icon issue on Mac or Windows. I'm guessing you tried restarting ST?
![screen shot 2015-02-05 at 10 23 14 am](https://cloud.githubusercontent.com/assets/458356/6062883/224bd0a8-ad21-11e4-950c-a8b01b343299.png)

Which keywords?

Also, can you test the keyword color change using a different syntax theme? Maybe use [Monokai Extended](https://packagecontrol.io/packages/Monokai%20Extended). 

Thanks for your help.

**Comment by giltig** [comment]
the keyword "this"

**Comment by frankyonnetti** [comment]
Thanks, I'll check it out. 
The screen shot I provided was in Windows 8.1. I can try Windows 7, is that what you're using?

**Comment by giltig** [comment]
Yes windows 7

**Comment by frankyonnetti** [comment]
Here is a screen shot from Windows 7 fresh install of Sublime Text. Sorry man, I can't reproduce it.

![screen shot 2015-02-06 at 8 12 02 pm](https://cloud.githubusercontent.com/assets/458356/6090233/9623671e-ae40-11e4-9d37-b2d1c511d7bc.png)

**Comment by mikerockett** [comment]
I'm seeing the same thing in Windows 10 with ST3114. In my case, PHP and Markdown icons are not showing. JSON and lnk is showing though...

**Comment by frankyonnetti** [comment]
Hi @mikerockett 

Installing multiple themes in Sublime Text can cause some sidebar icons to not show. Removing or disabling themes should fix the issue.

**Comment by mikerockett** [comment]
Thanks, @frankyonnetti - will be sure to give that a try. 👍
