### ISSUE TITLE
New File / Folder Bug

### ISSUE THREAD

**Issue by tschundeee** [frankyonnetti/gravity-sublime-theme#20]
Hi Frank,

first let me thank you for creating such a wonderful theme. Gravity Reverse is one of my favorite themes besides http://buymeasoda.github.io/soda-theme/ :) At the moment I prefer Mavericks and it also looks great under this OS X.

I found a little glitch when creating a new folder. The naming dialog in the bottom is cut off (see the attached screenshot).

![gravity theme glitch](https://cloud.githubusercontent.com/assets/49339/6284580/b1c1f1aa-b8f1-11e4-8998-7e6dbcfdbba7.png)

Is this reproducible for you?

Cheers 
Bijan

**Comment by frankyonnetti** [comment]
It's a common issue with ST. 
https://github.com/frankyonnetti/gravity-sublime-theme/wiki/Theme-Trouble-Shooting

**Comment by tschundeee** [comment]
Cool! I searched the issues but missed the wiki when filing this. Thx it now works as expected :) :+1:
