### ISSUE TITLE
indent drawing

### ISSUE THREAD

**Issue by giltig** [frankyonnetti/gravity-sublime-theme#21]
Hi,
After the change to Monokai extended the vertical indentation lines color became green (was blue which was more fitting the cursor...). Can you please change the indentation dashed lines color back to what it was.
Thanx.

![image](https://cloud.githubusercontent.com/assets/5754742/6502113/1685e1be-c329-11e4-8c53-7324efdbbf63.png)

**Comment by frankyonnetti** [comment]
Hey man, I changed it to the blue from before. So weird because the guid lines are gray on my Mac.

**Comment by giltig** [comment]
Thanx. 
By the way the previous green color in the html (attributes) was also better IMHO - the new one is too bright.
