### ISSUE TITLE
Find & Replace Bug

### ISSUE THREAD

**Issue by vinkla** [frankyonnetti/gravity-sublime-theme#24]
When running find and replace the third input field is below the fold? Potential bug?

![screen shot 2015-05-04 at 10 56 02](https://cloud.githubusercontent.com/assets/499192/7451051/30059628-f24c-11e4-96ba-56bb03b504d9.png)

**Comment by frankyonnetti** [comment]
Hey @vinkla 

You can find a solution here 
https://github.com/frankyonnetti/gravity-sublime-theme/wiki/Theme-Trouble-Shooting

**Comment by vinkla** [comment]
Cool, thanks!
