### ISSUE TITLE
Reverse Gravity: "Check for Updates..." Dialog is Dark on Dark

### ISSUE THREAD

**Issue by tschundeee** [frankyonnetti/gravity-sublime-theme#25]
Hey Frank,

just a minor "glitch" when clicking on "Check for Updates..." when using Reverse Gravity it is rendered Dark on Dark.
I guess it should match the rest of the Theme. What do you think?

Cheers Bijan
PS: Superb Job with this Theme! It should be default on OS X :+1:

**Comment by frankyonnetti** [comment]
Thanks @tschundeee 

Yeah that's a tough one. I'll see what I can do.

**Comment by tschundeee** [comment]
No stress. It's a very minor thing :)

**Comment by frankyonnetti** [comment]
This should be fixed in 2.1.2 release. Thanks @tschundeee
