### ISSUE TITLE
Sidebar Icons get overridden

### ISSUE THREAD

**Issue by tschundeee** [frankyonnetti/gravity-sublime-theme#26]
Hi Frank, since the last update somehow I am experiencing this strange behavior:

My Problem:
I am using latest ST3-Dev.

This theme comes with default file icons. 
When I have a package like "ShellScript" enabled, the themes file-icon disappears and no other icon is shown leaving a gap for this filetype. 
When I disable package "ShellScript" the sidebar file-icon reappears. The same happens for some other filetypes like for example .go.

I tried the https://github.com/karelvuong/st-fox/ theme and this theme shows its own icons for .go and .sh etc. and therefore works.

Do I need to add special versions of the default icons for filetypes that are not supported?
I can of course contribute back into the repo if this fixes it.

What do you think?

Cheers Bijan

**Comment by tschundeee** [comment]
I created a pull request that at least for me fixed the unexpected behavior.

**Comment by frankyonnetti** [comment]
I had the same problem with the SASS package. Disabling it fixed it for me. So I actualy tried the same fix as you but it didn't work 100% for me. Then I switched my theme to the default ST theme and all the icons showed. So I looked at the default theme files and it had the same amount of file type icons I do. So I wonder if it's a weird caching problem...

Is this the ShellScript package? I want to try to reproduce the error. https://packagecontrol.io/packages/Dotfiles%20Syntax%20Highlighting

**Comment by tschundeee** [comment]
I did not install a special ShellScript Package as far as I can tell:
Here is my package list.
{
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"All Autocomplete",
		"AngularJS",
		"AngularJS Snippets",
		"AutoFileName",
		"Better CoffeeScript",
		"Better Completion",
		"BracketHighlighter",
		"Brackets Color Scheme",
		"Browser Refresh",
		"CodeFormatter",
		"CoffeeComplete Plus (Autocompletion)",
		"Color Highlighter",
		"ColorPicker",
		"Colorsublime",
		"CSS Snippets",
		"CSScomb",
		"CSSLint",
		"Emmet",
		"GitGutter",
		"Github Color Theme",
		"GoOracle",
		"GoSublime",
		"Handlebars",
		"HexViewer",
		"HTML-CSS-JS Prettify",
		"HTMLBeautify",
		"LESS",
		"Less2Css",
		"nginx",
		"Numix Theme",
		"Package Control",
		"Schemr",
		"SFTP",
		"SideBarEnhancements",
		"SideBarGit",
		"SublimeCodeIntel",
		"SublimeLinter",
		"SublimeLinter-contrib-golint",
		"SublimeLinter-contrib-gotype",
		"SublimeLinter-contrib-jslint",
		"SublimeLinter-xmllint",
		"Terminal",
		"tern_for_sublime",
		"Theme - Aqua",
		"Theme - Fox",
		"Theme - Soda",
		"Themr"
	]
}

**Comment by frankyonnetti** [comment]
Your previous comment mentions you have the package "ShellScript" enabled?

**Comment by tschundeee** [comment]
I think ShellScript is a default package bundled with Sublime...

**Comment by frankyonnetti** [comment]
Oh right, I see that now, thanks. My guess is something on your end got corrupted. I'm not seeing the issue with ST3-Dev. The links below say it could be a corrupted preference file for ST or one of your installed packages. Did you try disabling all the 3rd party packages you have installed? 

I'll do some searching to see if I can find a more solid fix.

http://sublime-text-knowledge-base.readthedocs.org/en/latest/troubleshooting_theme_issues.html
http://sublime-text-knowledge-base.readthedocs.org/en/latest/how_to_solve_nearly_every_problem.html

**Comment by tschundeee** [comment]
I'll investigate and let you know as soon as I find something.

**Comment by tschundeee** [comment]
Error seems to be on sublime cache somehow. I noticed that when I uninstalled another theme that came with icons everything went back to normal.

**Comment by frankyonnetti** [comment]
Hey @tschundeee 

That's so funny, I just posted this in the wiki item #2. 
https://github.com/frankyonnetti/gravity-sublime-theme/wiki/Theme-Trouble-Shooting

**Comment by tschundeee** [comment]
Hey Frank that's really funny :) 
I finally solved this yesterday after installing a new theme. Maybe we should file this issue on the sublime forums?

**Comment by frankyonnetti** [comment]
Definitely. Go for it.
