### ISSUE TITLE
Code folding buttons are not visible

### ISSUE THREAD

**Issue by josip** [frankyonnetti/gravity-sublime-theme#28]
Code folding buttons are gone with the theme, even if I set them to be always visible (`"fade_folding_buttons":false`)

![screen shot 2015-05-26 at 12 18 40](https://cloud.githubusercontent.com/assets/11433/7810349/7ad57cb6-03a1-11e5-86a0-a9ad37ddcd0f.png)

For reference, this is how it looks like with the default theme:

![screen shot 2015-05-26 at 12 19 33](https://cloud.githubusercontent.com/assets/11433/7810341/753c031a-03a1-11e5-8dc7-24a2c2074eca.png)

**Comment by frankyonnetti** [comment]
I'm not seeing that issue. What version/build of Sublime Text are you using?

**Comment by josip** [comment]
Sublime 3, build 3083 on OS X 10.10.4. But I've been seeing it for a while now.

**Comment by frankyonnetti** [comment]
Can you try deleting the theme, restart ST and then reinstall the theme?

Might be a corrupted file from updating.
http://sublime-text-knowledge-base.readthedocs.org/en/latest/troubleshooting_theme_issues.html

**Comment by tschundeee** [comment]
Unfortunately I'm also experiencing the same issue. I did a clean install of ST3 Dev 3091 and only installed Package Control and Gravity. 
The light version doesn't show the code folding arrows on a bright color theme.

**Comment by tschundeee** [comment]
I guess it is because of this:

{
        "class": "fold_button_control",
        "attributes": ["expanded"],
        "layer0.texture": "Theme - Gravity/shared_assets/arrow_fold_down.png",
        "layer1.texture": "Theme - Gravity/shared_assets/arrow_fold_down.png"
    },

Theme - Gravity/shared_assets/arrow_fold_down.png is white and so cannot be seen on white BG.

**Comment by tschundeee** [comment]
This fixed it for me and works on dark and light backgrounds:

//
    // ! Fold button
    // ----------------------------------------------------------

    {
        "class": "fold_button_control",
        "layer0.texture": "Theme - Gravity/shared_assets/arrow_fold_right.png",
        "layer0.opacity": 0.3,
        "layer0.inner_margin": 0,
        "layer0.tint": [153,153,153],
        "layer1.texture": "Theme - Gravity/shared_assets/arrow_fold_right.png",
        "layer1.opacity": 0.0,
        "layer1.inner_margin": 0,
        "content_margin": [9, 7, 8, 6]
    },
    {
        "class": "fold_button_control",
        "attributes": ["hover"],
        "layer0.opacity": 0.9,
        "layer0.tint": [206, 206, 206],
        "layer1.opacity": 0.3
    },
    {
        "class": "fold_button_control",
        "attributes": ["expanded"],
        "layer0.texture": "Theme - Gravity/shared_assets/arrow_fold_down.png",
        "layer1.texture": "Theme - Gravity/shared_assets/arrow_fold_down.png"
    },

**Comment by tschundeee** [comment]
@frankyonnetti What do you think? The key seems to be layer.tint. Didn't want to create a pull request because I just quickly chose two colors and I guess you might first want to discuss this approach.

**Comment by frankyonnetti** [comment]
Good catch, thanks @tschundeee 

I'll review and implement a fix.

**Comment by frankyonnetti** [comment]
This is fixed in 2.1.4

Thanks
