### ISSUE TITLE
Proposal: Increase brightness of statusbar text.

### ISSUE THREAD

**Issue by tschundeee** [frankyonnetti/gravity-sublime-theme#29]
I found myself reading the infos in the bottom statusbar very often as some plugins offer nice context info there. As I'm looking there quite often I increased the brightness of the text to the same level as the text in the sidebar. 

@frankyonnetti What do you think about increasing the brightness of the bottom statusbar text for better readability in Default Gravity?

This is the setting I'm quite happy with:
// Status bar label
    {
        "class": "label_control",
        "parents": [{"class": "status_bar"}],
        "color": [169, 169, 169], <= Brighter and better readable
    },

The Default ST Theme also comes with a good contrast in the bottom statusbar.

**Comment by frankyonnetti** [comment]
Thanks @tschundeee, I lighten the text and I think it looks a lot better.

**Comment by tschundeee** [comment]
:+1: nice!
