### ISSUE TITLE
Rename Panel Bug

### ISSUE THREAD

**Issue by SalGnt** [frankyonnetti/gravity-sublime-theme#30]
When renaming a file, the bottom panel is not showed properly.

![reverse_gravity_bug](https://cloud.githubusercontent.com/assets/884093/8081494/a1eae5a4-0f75-11e5-9ab8-98f84a17e1bc.png)

I'm using ST Build 3083.

**Comment by frankyonnetti** [comment]
Hi @SalGnt you can find a fix here https://github.com/frankyonnetti/gravity-sublime-theme/wiki/Theme-Trouble-Shooting

**Comment by SalGnt** [comment]
Got it, thanks!
