### ISSUE TITLE
highlight_color_blue, should it affect selected text?

### ISSUE THREAD

**Issue by tsimmons** [frankyonnetti/gravity-sublime-theme#33]
After adding

    "highlight_color_blue": true

to my user preferences I was hoping that it would change the color of selected text (that is, text that is highlighted using click-and-drag or shift + cursor keys) because I've always found the default colors for highlighted text to be hard to see.

I don't see any difference, however, so my question is: should it be with this setting in place?

Thanks &
Cheers,

Toby

**Comment by frankyonnetti** [comment]
Hi @tsimmons 
I didn't add blue color highlights to the syntax colors, just the UI. Tabs, sidebar and tooltips.

**Comment by tsimmons** [comment]
Okay, fair enough. Apparently I have something else going on as well, because I don't see *any* difference with this setting (I'm on Yosemite):

Here it is with it set true:
<img width="1392" alt="screen shot 2015-08-31 at 10 51 23 am" src="https://cloud.githubusercontent.com/assets/366120/9583024/93e15df0-4fce-11e5-84b6-07e45b733dc6.png">

Here it is with it removed from settings (and ST3 restarted):
<img width="1392" alt="screen shot 2015-08-31 at 10 51 55 am" src="https://cloud.githubusercontent.com/assets/366120/9583036/a59ff7c2-4fce-11e5-9470-73b1af92a4bf.png">

What should I be seeing?

Thanks again &
Cheers,

Toby

**Comment by frankyonnetti** [comment]
That looks like the default theme. Try adding the UI theme to your preferences as well and restart Sublime. 
`"theme": "Gravity.sublime-theme"` or, `"theme": "Reverse Gravity.sublime-theme"`

**Comment by tsimmons** [comment]
Duhr. I was using the Gravity color scheme, without the theme.

Thanks!

**Comment by frankyonnetti** [comment]
It happens to the best of us :)
