### ISSUE TITLE
Tabs.

### ISSUE THREAD

**Issue by tschundeee** [frankyonnetti/gravity-sublime-theme#34]
Hi Frank,

thx for releasing 2.5 of gravity. I like the font-size changes in the sidebar to 12px. 

I am not so happy with the tabs in the top and liked the old tabs better. These are the problem spots IMHO:
- When a tab is inactive it has full height to the top (which is nice and I like it).
- When a tab is then active it all of a sudden has lower height and some margin to the top. the label is also not vertically centered anymore (also the close icon). It feels as if the label hits its head on the top border of the tab.

The tabs feel not so predictable anymore. The default tabs also have margin to the top but they don't change the shape from full height to lower height all of a sudden when it gets selected.

Is there an option to get the "old" tabs back?

**Comment by frankyonnetti** [comment]
Hey @tschundeee 
Sorry to disappoint. I am using the setting `"tab_height_tall": true` in my personal preferences if that helps. 

In the meantime I'll see about tweaking the new tabs so all elements balance vertically. But I do like the gap at the top of the active tab.

To use the older version, remove the Package Control version of Gravity. Then download the 2.1.4 tag and manually add it to your packages directory. https://github.com/frankyonnetti/gravity-sublime-theme/tree/2.1.4

**Comment by tschundeee** [comment]
Hey Frank,

the new tabs really look better with "tab_height_tall": true :+1: 
Would it be possible to make the old tab style default if "tab_height_tall" : false ?

Cheers Bijan

**Comment by tschundeee** [comment]
Now I know why the new tabs feel stranger to me than the old ones: they are farer away from apples own UI. Safari and Finder are a good example how apple designs tabs. The old style tabs were more close to the apple standard ui and therefore felt more native than the new ones here. 

But this is just my opinion and this is your theme and of course you are in control of the design etc. 

Just thought that if you want to position Gravity more or less as the default sublime ui for osx > 10.9 (everything below the soda theme is default) then it would make sense to keep closer to the original apple ui.

Let me know what you think :)

**Comment by frankyonnetti** [comment]
Hey @tschundeee 
I removed the visual gab above the active tab in 2.5.1. You're right, that looks better :-)

**Comment by tschundeee** [comment]
I thought of adding a theme variant that has the new osx tabs recreated?
I mean making the tabs behave exactly like the ones in safari, xcode or finder.
I don't know if this is possible for sublime to have the close icon on the left side and to hide it until mouse hovers. Is this possible or is sublime only showing close button on the right?

**Comment by frankyonnetti** [comment]
I know you can hide the close icon, but I don't think you can move it to the left side of the tab. 
To see if you can, try to find a ST theme that has a close button on the left and review it's code.
