### ISSUE TITLE
Mixed color-scheme in Reverse Gravity theme

### ISSUE THREAD

**Issue by doyaklee** [frankyonnetti/gravity-sublime-theme#35]
Hi, Frank.
Thanks for providing great looking theme!
I just have one problem about color scheme.
I applied Reverse Gravity theme, but it seems that the color scheme is sort of mixed as opposed to the screenshot in the Readme.md. Here is a screenshot for my user setting.
![colorshot](https://cloud.githubusercontent.com/assets/14086459/9623482/5a31d1f6-510f-11e5-99c3-7fb2b1fbef06.jpg)
Could you tell me what the problem is? Thanks!

**Comment by frankyonnetti** [comment]
Hi @doyaklee 
I would suggest using the `Mac Classic` color scheme along with the **Reverse Gravity** UI.
I would also add these two additional settings to your preferences:
`"tab_font_small": true`
`"tab_height_tall": true`

**Comment by doyaklee** [comment]
Hi @frankyonnetti 
It works very nicely. Thanks!
