### ISSUE TITLE
Sublime 3101 DEV Added Panel Switcher to status bar

### ISSUE THREAD

**Issue by GoBijan** [frankyonnetti/gravity-sublime-theme#36]
Hi Frank,
the default theme now has a little menu in the status bar (lower left).
Would be cool if it could be added to Gravity Theme :)
Cheers Bijan

**Comment by GoBijan** [comment]
Okay I patched it into Gravity. I will create a pull request now :)

**Comment by frankyonnetti** [comment]
Awesome, thanks Bijan!
I'll push it out today or tomorrow so it's updated through packages. I'll need to update my assets first. I use grunt to compile my themes. Plus I'll want to make a light theme panels icon as well.

**Comment by GoBijan** [comment]
Sorry I saw that in my last pull request I loaded the panels.png asset from the default theme instead of the themes own assets. I also added an adjusted panels.png for the Reverse Gravity variation.
Hope you can make use of it, with or without grunt :D

**Comment by frankyonnetti** [comment]
OK, update has been pushed to Package Control!
