### ISSUE TITLE
Sidebar highlight is light gray

### ISSUE THREAD

**Issue by alecthomas** [frankyonnetti/gravity-sublime-theme#39]
Hello,

First off, I love the nice clean design of this theme. Thanks.

I realise this may not be a problem with Gravity theme, but both the default theme and Soda Light work correctly (ie. the highlight colour is readable).

This is what the highlight colour in my sidebar looks like, whether `highlight_color_blue` is true or false.

![image](https://cloud.githubusercontent.com/assets/41767/13384031/969be0be-dee5-11e5-8f41-5281b33db682.png)

As you can imagine, it's difficult to find with a long file list.

Any ideas what could cause this?

Thanks,
Alec

Edit: the line under tabs does change between blue and gray, with this setting.

**Comment by frankyonnetti** [comment]
If you have other themes installed, disable them, restart Sublime and see if that works.

**Comment by frankyonnetti** [comment]
Sorry, I see what you're saying. I had removed the blue highlight background and made it just a line on the left side; to match the tabs.

![screen shot 2016-03-02 at 1 37 46 pm](https://cloud.githubusercontent.com/assets/458356/13470901/3b69c934-e07c-11e5-99ad-f512a32d5310.png)

**Comment by alecthomas** [comment]
Can that be restored, or the colour at least made more differentiable from the background? In large code bases it makes it hard to quickly find the current file. This is particularly a problem where the same file name is used a lot (eg. Python's `__init__.py`).

**Comment by alecthomas** [comment]
(FWIW I thought the blue background was fine, and fit in quite well)
