### ISSUE TITLE
Option tab_height_short not defined

### ISSUE THREAD

**Issue by yckart** [frankyonnetti/gravity-sublime-theme#40]
As noted here https://github.com/frankyonnetti/gravity-sublime-theme/issues/11#issuecomment-70765683, you've added a `tab_height_short` option in *2.0.1*. Tried it, but nothing was changed. I looked in to the source files and it's just not defined in all of those `*.sublime-theme` files.

Would nice to have slightly smaller tabs than per default, maybe `25px` or `30px`.

*Also, the padding on them is a bit too wide, for my opinion.*
(Long filenames get clamped and if there are some more files opened, with `index.css` and `index.js` it's just not clear what tab contains the right contents.

**Comment by frankyonnetti** [comment]
I'll add it back. Will post here when it's pushed.

**Comment by Antherkiv** [comment]
It's not the same topic, but do you considered to put the tab highlight in the top?

**Comment by frankyonnetti** [comment]
@yckart 
Added the "short tab height" settings back to release 3.0.1.
use: "tab_height_short": true

**Comment by frankyonnetti** [comment]
@Antherkiv thanks for asking. 
I have tried it, but I don't like the way it looks against the window toolbar on the Mac.
