### ISSUE TITLE
A style bug

### ISSUE THREAD

**Issue by yutent** [frankyonnetti/gravity-sublime-theme#41]
The input field like this, while adding new file/ folder,  or rename a file /folder .

![image](https://cloud.githubusercontent.com/assets/11972650/13641372/2284833c-e653-11e5-8f46-7b2ea6f9abd8.png)

**Comment by frankyonnetti** [comment]
Hi @yutent 
There is a fix posted here:
https://github.com/frankyonnetti/gravity-sublime-theme/wiki/Theme-Trouble-Shooting

**Comment by yutent** [comment]
Sorry about that I gave you  vague description.
It shows well when use "find" command. But wrong in creating a new file  or folder.

**Comment by frankyonnetti** [comment]
Did you try pulling up on it?

**Comment by yutent** [comment]
Yes, I did,but it didn't work.
However It works well this morning due to rebooting my computer.  Thanks for your patience again!
