### ISSUE TITLE
Python icons

### ISSUE THREAD

**Issue by elcone** [frankyonnetti/gravity-sublime-theme#42]
Icons for python files won't display, how can I display de default icon?, great theme by the way!

**Comment by kaansoral** [comment]
When I tried this theme, many icons didn't display either, I went back to Flatland for it's simplicity

**Comment by frankyonnetti** [comment]
Icons not displaying in the sidebar is a bug with Sublime. The fix is to disable themes not in use.

No. 2 issue here:
https://github.com/frankyonnetti/gravity-sublime-theme/wiki/Theme-Trouble-Shooting

**Comment by elcone** [comment]
thank's! removing the themes I don't use fixed the problem
