### ISSUE TITLE
One dark color scheme

### ISSUE THREAD

**Issue by giltig** [frankyonnetti/gravity-sublime-theme#43]
Hi, 
while your gravity one theme is beautiful,
the one dark color scheme that you recommended is not being supported anymore according to the README.

Do you have any recommendations for other color schemes that will go with the Gravity One theme?

**Comment by frankyonnetti** [comment]
Sorry, no I don't. I've been using it for a long time now and it works good for me.

**Comment by frankyonnetti** [comment]
Hey @giltig 
Came across this color scheme. Looks really nice.
https://github.com/sonph/onehalf
