### ISSUE TITLE
Status bar overlaps menu

### ISSUE THREAD

**Issue by katzer** [frankyonnetti/gravity-sublime-theme#45]
Hi, when I choose any context action like "New File..." the input file will be overlapped by the status bar. This happen only with your gravity theme.

I am using v3.0.4 but its present for long since I am using it.

<img width="315" alt="overlapping" src="https://cloud.githubusercontent.com/assets/2039384/18760709/7d90b92c-8102-11e6-9f6e-d19fa24c0345.png">

Would be great to see it fixed in future and thanks anyway for your great theme!

**Comment by frankyonnetti** [comment]
Hey @katzer check out issue #1 
https://github.com/frankyonnetti/gravity-sublime-theme/wiki/Theme-Trouble-Shooting

Hope that helps

**Comment by katzer** [comment]
@frankyonnetti Fixed!
