### ISSUE TITLE
Add margin/padding between tabs and first line?

### ISSUE THREAD

**Issue by Railslide** [frankyonnetti/gravity-sublime-theme#47]
Hi,
Thanks for a great theme!

Is there a way to increase the distance between tabs and the first line of the content panel? 

![screen shot 2017-02-07 at 08 53 04](https://cloud.githubusercontent.com/assets/5789142/22682499/3af85304-ed13-11e6-9534-529a1e1ad1e0.png)

I've tried playing around with the user settings file, but without luck.

**Comment by frankyonnetti** [comment]
Hi @Railslide 
Unfortunately there isn't. I tried adjusting (hacking) it at one time, but the tight space under the tab was slightly better than my results.

**Comment by Railslide** [comment]
Oh well, I guess I'll have to live with it then - thanks! :)

**Comment by dndrsn** [comment]
This always bothers me.  I have seen, in some themes, extra visual space in the tab image below what is meant to visually look like the bottom of the tab.  The effect only works, however, if the background color of the color scheme matches the color of the "fake space" in the tab image.  I'm sure that doesn't make any sense.
