### ISSUE TITLE
Dark Tabs for Reverse Gravity theme

### ISSUE THREAD

**Issue by ayanb1991** [frankyonnetti/gravity-sublime-theme#48]
When using Gravity Monokai theme with Reverse Gravity .tmtheme, white tabs with monokai dark color scheme looking very odd. Can you please provide some sort of settings where I can make tabs 'Dark' while using the Reverse Gravity theme.

Otherwise theme looks very nice. Thanks.

**Comment by frankyonnetti** [comment]
Hi @ayanb1991 
I've tried that before and it didn't improve the look when using a dark code theme. Works best with light code themes.
