### ISSUE TITLE
Sidebar header disappears when sidebar shrinks below a certain width

### ISSUE THREAD

**Issue by joejoinerr** [frankyonnetti/gravity-sublime-theme#50]
When reducing the width of the sidebar beyond a certain point, the sidebar header is replaced by a blank white space.

<img width="198" alt="screen shot 2017-12-31 at 15 00 22" src="https://user-images.githubusercontent.com/2454320/34462439-0fff28d2-ee3c-11e7-93b1-4536c290d346.png">

Tested on a Mac mini and MacBook Pro both running macOS 10.13.2.
Sublime Text v3.0 Build 3143.
Gravity One theme.

"gravity_highlight_color_blue": true
"gravity_sidebar_header": true
"gravity_tab_font_small": true
"gravity_tab_height_short": true

**Comment by frankyonnetti** [comment]
Thanks @joejoinerr 
That's funny, I have never reduced the sidebar at that width before. But I see the bug when I do.

**Comment by frankyonnetti** [comment]
Hi @joejoinerr 
I wasn't able to fix the header disappearing at a narrow width.
But the white background should be gone now which looks a little better. 

_tag 3.0.9_
