### ISSUE TITLE
Blue color for js functions in html files

### ISSUE THREAD

**Issue by Nemesis19** [frankyonnetti/gravity-sublime-theme#51]
Dear Developer,

I'm using the gravity one theme and for a while I could see the functions in angular html files the same blue used for the functions in typescript files.

Now it has disappeared and returned the normal red as before...

I was really enjoying that blue in html files...is it possible to implement it?

I'm sorry but I have no idea how it happened...

**Comment by frankyonnetti** [comment]
The color scheme for Gravity One is just a fork from 
https://github.com/IceTimux/one-dark-sublime-text-3-color-scheme

You can try using this color scheme instead to see if it helps
https://packagecontrol.io/packages/One%20Half%20Color%20Schemes

**Comment by Nemesis19** [comment]
Thanks, already tried...doesn't work. Anyway it's not that important.

Thanks for the help!

Can I suggest you to add a new colorscheme variant based on this?
https://marketplace.visualstudio.com/items?itemName=azemoh.one-monokai

it's a kind of fusion between One Dark and Monokai, very readable and with a very good color separation.

Thanks anyway, gravity theme so far is the best sublime theme 👍

**Comment by frankyonnetti** [comment]
I'll take a look. Thanks!
