### ISSUE TITLE
gravity one doesnt look right

### ISSUE THREAD

**Issue by crapthings** [frankyonnetti/gravity-sublime-theme#54]
<img width="1632" alt="Screen Shot 2019-04-05 at 15 28 39" src="https://user-images.githubusercontent.com/1147704/55611247-87c55900-57b7-11e9-9705-27ad15f90022.png">

**Comment by frankyonnetti** [comment]
Hi @crapthings 
Not sure, are you referring to the color scheme? If so, go to "Preferences > Color Scheme.." and select "One Dark Gravity".
