### ISSUE TITLE
Feature request: bold font for active tab

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [frankyonnetti/gravity-sublime-theme#56]
I find your theme to be one of very few that makes inactive tab titles legible. However, I'd like to make the _active_ tab font **bold** - but don't see how. Thanks. I've Sublime Text 3 and the latest (Sublime repository) version of your theme.

**Comment by frankyonnetti** [comment]
As you noted, that option is not currently available for this theme. But you can always override theme settings by placing the following gist (file) in your `Sublime Text 3/Packages/User`.

https://gist.github.com/frankyonnetti/3d629c418afe72153d28cc5b234ec7e7

You can find that directory by selecting "Browse Packages..." menu un preferences.

**Comment by LinuxOnTheDesktop** [comment]
That works well (though I had to change the name of the file to 'Gravity.sublime-theme', because that is the version of the theme that I use). Thank you. Screenshot:

![image](https://user-images.githubusercontent.com/47056543/58926258-76aab100-8742-11e9-8abd-f09f8180c4ab.png)


Even better would be an option within the package for this setup.

**Comment by frankyonnetti** [comment]
This is added in version 3.5.5:
`"gravity_selected_tab_bold": true`
