### ISSUE TITLE
On one file, the scrollbar disappears

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [frankyonnetti/gravity-sublime-theme#57]
I really like this theme (or set of themes) but, on Windows (8.1) and Linux (Mint 19.1 Cinnamon), in one of my files - which I attach - the scroll bar disappears. I have `"overlay_scroll_bars": "disabled"` in my Sublime settings user file. Changing the viewed file, or changing theme, fixes the problem.

[log.txt](https://github.com/frankyonnetti/gravity-sublime-theme/files/3234828/log.txt)

**Comment by frankyonnetti** [comment]
Thanks @LinuxOnTheDesktop, I'll see about adding a fix.

**Comment by LinuxOnTheDesktop** [comment]
Great. I should add that I have the problem with all the subthemes.

**Comment by frankyonnetti** [comment]
Hi @LinuxOnTheDesktop, I pushed a fix this in version 3.5.5
Thanks
