### ISSUE TITLE
Feature request: Bold font for folders

### ISSUE THREAD

**Issue by Myrronth** [frankyonnetti/gravity-sublime-theme#58]
Similar as #56. I currently use the High-Sienna theme and would switch to the Gravity theme if I could only make the folders in the project navigator stand out more.

High-Sienna has a setting for rendering the folder names in bold:
`"bold_folder_labels": true`

**Comment by frankyonnetti** [comment]
Hi @Myrronth 
You can bold the folder label by using this theme override settings file:
https://gist.github.com/frankyonnetti/0303c03c25cf7726b941030d1684bc71
