### ISSUE TITLE
Reverse Gravity - quick open focused item path highlight is unreadable

### ISSUE THREAD

**Issue by dndrsn** [frankyonnetti/gravity-sublime-theme#59]
Reverse Gravity uses the same white color to highlight matches in the file path for the quick launch for the focused item.  It's very hard to read agains the light gray background.   

![image](https://user-images.githubusercontent.com/1944277/79564500-c8b7a500-807c-11ea-9fea-e4ac85bdb058.png)

It uses a darker gray for the non-focused items.

**Comment by dndrsn** [comment]
FWIW, I did a local override of line 604 the theme file:
~~~JSON
        "selected_match_fg": [96, 96, 96]
~~~
to get this:
![image](https://user-images.githubusercontent.com/1944277/79571930-0a028180-808a-11ea-9d7d-8e6587606e77.png)

**Comment by frankyonnetti** [comment]
Thanks @dndrsn for the find and details on the fix. I updated the theme and pushed it to a new tag release.
