### ISSUE TITLE
git - change font color in file tree for ignored items

### ISSUE THREAD

**Issue by sobaw98247** [frankyonnetti/gravity-sublime-theme#61]
Hey,
how can I change color/opacity for ignored files?

Screen from Meetio Theme:
![image](https://user-images.githubusercontent.com/66990562/89415344-045da400-d72c-11ea-8a6b-23245d3080ea.png)

Gravity One:
![image](https://user-images.githubusercontent.com/66990562/89415414-18a1a100-d72c-11ea-94dc-61d025ad2b24.png)

**Comment by frankyonnetti** [comment]
I didn't realize that was possible in ST. I'll have to take a look.

**Comment by sobaw98247** [comment]
Here's a little more about this: https://www.sublimetext.com/docs/3/git_integration.html

> Files and folders displayed in the side bar will include a status badge along the right-hand edge, when modified. This includes files and folder in the Folders section of the side bar, along with files in the Open Files section. **Ignored files and folders are de-emphasized in the side bar by reducing the opacity of the name**.

I added 
```
{
	"class": "sidebar_label",
	"parents": [{"class": "file_system_entry", "attributes": ["ignored"],}],
	"opacity": 0.5,
}
```

and it works for me :)

PR: https://github.com/frankyonnetti/gravity-sublime-theme/pull/62

**Comment by frankyonnetti** [comment]
Thanks for your help on this @sobaw98247 , it's a really cool feature. 
I'm going to dim the folder & icons as well and add it to the other 2 themes. I hope to push in the next day or so.

**Comment by frankyonnetti** [comment]
This change is in tag release 3.5.9
