### ISSUE TITLE
[Gravity One] git - change line colors

### ISSUE THREAD

**Issue by sobaw98247** [frankyonnetti/gravity-sublime-theme#63]
Color of changed line in gutter: 
![image](https://user-images.githubusercontent.com/66990562/91934686-3ee73c00-ecec-11ea-95d6-bb8ced6a1578.png)

doesn't correspond with colors in minimap: 
![image](https://user-images.githubusercontent.com/66990562/91934723-51fa0c00-ecec-11ea-8892-dfe855375e8b.png)

**Comment by frankyonnetti** [comment]
Is that a ST version 4 feature?

**Comment by sobaw98247** [comment]
Screens are from ST4 but I think it is even in ST3 :)

**Comment by frankyonnetti** [comment]
Is there a package drawing the git diff in the minimap; maybe GitGutter? Because I cannot find a setting for it.

**Comment by sobaw98247** [comment]
You're right, it's from GitGutter. I was convinced that that was ST feature. Sorry :)
