### ISSUE TITLE
Gravity One - broken links color in Command Paletter

### ISSUE THREAD

**Issue by sobaw98247** [frankyonnetti/gravity-sublime-theme#64]
Hey,  
these link should be like this?

![image](https://user-images.githubusercontent.com/66990562/97998402-55903900-1dea-11eb-9cb5-b6eb8fd1bcd2.png)

**Comment by frankyonnetti** [comment]
Oh yeah, that's terrible. I'll take a look. Thanks.

**Comment by frankyonnetti** [comment]
This is fixed now in 3.6.0. Thanks.
