### ISSUE TITLE
One Dark: missing all punctuation.* scopes

### ISSUE THREAD

**Issue by rwols** [frankyonnetti/gravity-sublime-theme#65]
I like this color scheme. Thanks for your work.

<img width="522" alt="image" src="https://user-images.githubusercontent.com/2431823/99147493-b1c44a00-2681-11eb-864d-e7d47d2ecae8.png">

However:

- `variable.parameter` has the same color as `variable.function` (both red). It would be nice if `variable.parameter` had a different color as function arguments are definitely a different concept than callables.
- I'm missing `punctuation` scopes like `punctuation.section`, `punctuation.group`, `punctuation.accessor`, `punctuation.definition.variable` and `punctuation.definition.string`.

**Comment by frankyonnetti** [comment]
Hi @rwols 
Honestly that file is so old (XML) it could use a rebuild in the new way for writing schemes (JSON). Which I hope to do some day soon 🤷‍♂️. But if you would rather have it sooner, do you mind trying to fix it and create a pull request?

**Comment by rwols** [comment]
I'm not sure why this got closed. punctuation scopes are still missing.

**Comment by rwols** [comment]
By the way apologies in advance if I come across as too demanding and/or brief but I'm just documenting some shortcomings and overall really like the color palette. I don't have much more free time.

**Comment by frankyonnetti** [comment]
Hi @rwols sorry for taking so long to get to you. I spent more time on this and have come to the conclusion that I don't know enough about C++ to make good judgements on a color scheme that supports it.

This leaves us with two options:

1. You can try to fix the scheme when you have time and provide a pull request with the fixes.
2. Try out [One Half Color Schemes](https://packagecontrol.io/packages/One%20Half%20Color%20Schemes) package. I tried it and it may be worth you trying it as well.

Sorry I couldn't be more helpful.

**Comment by rwols** [comment]
Hi Frank, not a problem. I'll see what I can do about the selectors. Just covering all scopes from the "minimal scope coverage" [here](https://www.sublimetext.com/docs/3/scope_naming.html) should work for all languages (not just C++).

**Comment by frankyonnetti** [comment]
Thanks @rwols !!
All 3 PRs merged and pushed. Should show in Package Control within the hour as 4.0.2
