### ISSUE TITLE
One Dark: storage.modifier is too similar to variable.parameter

### ISSUE THREAD

**Issue by rwols** [frankyonnetti/gravity-sublime-theme#68]
~~I believe variable.parameter now receives a color? Nice work 👍 although~~ (EDIT: Never mind, it was already reddish) I do think the distance in color between `storage.modifier` and `variable.parameter` is too short now:

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/2431823/101994132-468d8800-3cc0-11eb-97dd-b59a2fbfa4b3.png">

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/2431823/101994145-54430d80-3cc0-11eb-9f23-bf8973f858ce.png">

**Comment by frankyonnetti** [comment]
Can try installing one of these packages? They help improve C++ syntax in Sublime.

- https://packagecontrol.io/packages/C%2B%2B11
- https://packagecontrol.io/packages/C%2B%2B%20Starting%20Kit

**Comment by rwols** [comment]
Those syntaxes are unmaintained. The default one is pretty good.

**Comment by rwols** [comment]
I still think this is an issue. Member variables, function arguments, storage modifiers are all the same color (red).

**Comment by rwols** [comment]
But I'll see if I can try something myself.
