### ISSUE TITLE
One Dark Gravity: bad keyword color

### ISSUE THREAD

**Issue by sprat** [frankyonnetti/gravity-sublime-theme#72]
The "await" keyword color in python is broken in the latest release. See attached screenshot.

![bad-keyword-color](https://user-images.githubusercontent.com/577183/104455336-6fe35180-55a7-11eb-957c-86607db9ff61.png)

**Comment by frankyonnetti** [comment]
Thanks @sprat 
Can you provide that code, or part of it, so I can test and fix?

**Comment by sprat** [comment]
Here it is: [host.py.zip](https://github.com/frankyonnetti/gravity-sublime-theme/files/5810861/host.py.zip) (sorry for the zip file, I didn't found another way to attach the file)

**Comment by frankyonnetti** [comment]
Thanks @sprat 
How does this look now?
<img width="475" alt="Screen Shot 2021-01-16 at 12 45 47 PM" src="https://user-images.githubusercontent.com/458356/104819023-ee82fd80-57f8-11eb-9a0e-fbce5ccf2c3a.png">

**Comment by sprat** [comment]
Much better ;) You removed italics also ?

**Comment by frankyonnetti** [comment]
Thank you. No, italics are still there, I have it turned off in my preferences. I'll push to package control soon. Usually takes an hour to show up.

**Comment by sprat** [comment]
Many thanks! Did I say I really like this theme, it's very easy for the eyes: thank you for this!

**Comment by rwols** [comment]
Yeah I broke that in 41e7d6fea955861b9f95918d9efed2475a6be59a. Sorry about that.

**Comment by rwols** [comment]
I still do think we should differentiate better between the different keywords

```
keyword.control
keyword.operator
keyword.declaration
```

**Comment by sprat** [comment]
Solved for me
