### ISSUE TITLE
Light color scheme used in screenshot / recommendation

### ISSUE THREAD

**Issue by mjbaldwin** [frankyonnetti/gravity-sublime-theme#73]
Hi, I've been searching for a good light color scheme for ST3 and can't find a satisfying one anywhere... until I saw the one used in the light screenshot for Gravity.

In Package Control I know you say "Sorry, no syntax color scheme supplied. But I'm sure there are plenty to choose from in Package Control."

But could you tell me which color scheme you used there? And I might recommend even putting it in the Package Control description there too. Thanks so much.

**Comment by mjbaldwin** [comment]
Thanks so much for the reply!

Sadly it doesn't seem to exactly match either of those, at least not in their current forms. :S

The built-in "Brackets" is all blue/green/orange, while your screenshot is equivalently red/purple/green.

One Half is a little closer, but it uses orange where your screenshot uses purple...

Unless you modified the colors further -- I may wind up having to do that. But thanks again!!

**Comment by frankyonnetti** [comment]
Are you using ST3? I'm using v.4 so maybe it changed. See attached v.4 Brackers scheme.
[Breakers.sublime-color-scheme.zip](https://github.com/frankyonnetti/gravity-sublime-theme/files/6117944/Breakers.sublime-color-scheme.zip)

**Comment by mjbaldwin** [comment]
Ah ha that's it! Yes I'm on ST3. But installed that and it's perfect. Thanks so much, much appreciated.
