### ISSUE TITLE
Menu stuck in hamburger form

### ISSUE THREAD

**Issue by CosmicQueso** [frankyonnetti/gravity-sublime-theme#74]
I updated Sublime Text to build 4107 (on Windows 10) today and had been using Gravity for a while.

After updating I noticed that the menu bar style was changed to a hamburger menu. Is there any way I can go back to the expanded form of the menu?

I have tried to poke around in the user settings and the theme settings, but have had no luck finding how to get the menu back to its expanded form.

**Comment by frankyonnetti** [comment]
It's part of ST4 and custom Windows titlebar. Can you try adding `"disable_custom_title_bar": true` in your preferences?

https://forum.sublimetext.com/t/st4-menu-bar-missing-in-windows-10/57662/11

**Comment by CosmicQueso** [comment]
I attempted this in both the theme settings and the sublime settings 

A snippet of Theme Settings  (Preferences > Customize Theme):
```
// Documentation at https://www.sublimetext.com/docs/themes.html
{
	"variables":
	{
		"disable_custom_title_bar": true
	},
	"rules":
	[
	]
}
```
A snippet of User Settings (Preferences > Settings):
```
{
	"color_scheme": "Packages/Color Scheme - Default/Monokai.sublime-color-scheme",
	"font_size": 11,
	"gravity_highlight_color_yellow": true,
	"gravity_sidebar_header": true,
	"gravity_tab_height_short": true,
	"gravity_title_bar": true,
	"ignored_packages":
	[
		"Vintage",
	],
	"theme": "Gravity.sublime-theme",
	"dark_theme": "Gravity One.sublime-theme",
	"light_theme": "Adaptive.sublime-theme",
	"disable_custom_title_bar": true
}
```

**Comment by frankyonnetti** [comment]
Sorry, guess I'll have to dig in more. Hope to get back to you soon.

**Comment by CosmicQueso** [comment]
Okay, thank you!

**Comment by frankyonnetti** [comment]
Do you have `gravity_title_bar` set to `true` in preferences? If so, set it to false. If that still doesn't work, try adding `"themed_title_bar": false` to your preferences.

**Comment by CosmicQueso** [comment]
The first one got it, thank you for your help!
