### ISSUE TITLE
Sublime Text 2 Icon download link doesn't work

### ISSUE THREAD

**Issue by sunyang713** [frankyonnetti/gravity-sublime-theme#75]
Looks like the bitly URL expired or something. Are the icons still available?

**Comment by frankyonnetti** [comment]
Hi @sunyang713, I tested and they all downloaded for me. Can you try again?

**Comment by sunyang713** [comment]
Ah, I clicked on the icon images themselves and it worked. I think the text-link has a typo. Created a PR.
