### ISSUE TITLE
.js file / Gravity One function name color issue

### ISSUE THREAD

**Issue by Borsti26** [frankyonnetti/gravity-sublime-theme#77]
Hi,

i use:
![image](https://user-images.githubusercontent.com/2920507/121523315-5d563280-c9f6-11eb-870e-b6652b948dd3.png)

and in .js files the function ther are text in the same color as the background:
![image](https://user-images.githubusercontent.com/2920507/121523423-7e1e8800-c9f6-11eb-944a-c172a142e6e5.png)

There are two lines with "test" written the second is marked. 

BR
René

**Comment by frankyonnetti** [comment]
I can't reproduce it. Can you try uninstalling and reinstalling Gravity?

![Screen Shot 2021-06-13 at 11 12 36 AM](https://user-images.githubusercontent.com/458356/121813119-a269a700-cc38-11eb-8e4a-5fa5a8002537.png)

**Comment by Borsti26** [comment]
Hi,

thanks. 
I deinstalled it and find out the theme did not complete removed in the Folder.
"C:\Users\%User%\AppData\Roaming\Sublime Text 3\Packages\User\Color Highlighter\themes"

After delete manually the files and install it again it work like a charm.

Thanks for you hint and your nice Theme.

BR
René
