### ISSUE TITLE
Fails to Respect the "hide_tab_scrolling_buttons" Preference

### ISSUE THREAD

**Issue by bdkjones** [frankyonnetti/gravity-sublime-theme#83]
Setting `"hide_tab_scrolling_buttons": true` in the `Preferences.sublime-settings` file has no effect; the "tab scrolling" chevrons are still displayed when Gravity is the active theme:

<img width="642" alt="Screenshot 2023-08-30 at 16 21 36" src="https://github.com/frankyonnetti/gravity-sublime-theme/assets/926566/48814c9f-2db4-4e99-9a14-04adab52dd80">

I'd really like to remove these buttons, as they're pointless clutter. Thanks!

## Context

- Sublime 4, build 4152
- Latest version of Gravity Theme installed via package control on 30 August 2023.

**Comment by frankyonnetti** [comment]
Oh shit, Bryan Jones. Thanks for using my theme. Just pushed an update (4.0.5), let me know if it doesn't work.

**Comment by bdkjones** [comment]
Works perfectly! And that's a *world record* for response-to-fix time. If only you ran Developer Relations at Apple...
